#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#   Listens on port 80.
#   Returns a page containing "Hello World!" when queried
#   at the root with a curl GET request.

sudo apt-get update
sudo apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.html

sudo service nginx restart
