#!/bin/bash
chmod a+X 0-iam_betty 10-mirror_permissions 11-directories_permissions 1-who_am_i 2-groups 3-new_owner 4-empty 5-execute 6-multiple_permissions 7-everybody 8-James_Bond 9-John_Doe README.md
