#!/usr/bin/env bash
# What’s keeping your Ubuntu container’s Nginx installation from listening on port 80?
# Nginx must be running, and listening on port 80

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
