#!/usr/bin/env bash
# Displays the contents of the file `/etc/passwd`.
# Displays the username, user id, and user home directory path only.

while LINE= read -r passwd; 
do
  echo "$passwd" | cut -d ':' -f 1,3,6
done < "/etc/passwd"
