#!/usr/bin/env bash
# Script that parses Apache logs in list format.
#  Groups visitors by IP and HTTP status code.
#  Displays the number of occurrences, IP, and HTTP status
#+ code of each log, in sorted order.

awk -F' ' '{ print $1 " " $9 }' apache-access.log | sort | uniq -c | sort -nr
